### ISSUE TITLE
extension displays error when multiple packages referenced in settings.json

### ISSUE THREAD

**Issue by bicarbon8** [vmikeska/vsc-npm-switcher#3]
if multiple packages are referenced in the settings.json file then an error of `Cannot read property 'split' of undefined` is displayed and the extension's sidebar panel no longer displays any packages.

**Example settings.json:**
```json
{
    "extensions.ignoreRecommendations": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "window.zoomLevel": 0,
    "dependencyDebugger.libraries": [
        {"name":"sample-one", "path":"../sample-one"},
        {"name":"sample-two", "path":"../sample-two"}
    ]
}
```

NOTE: if only one package is referenced in the settings.json file then the extension is able to parse it successfully

OS Where issue experienced: Windows 10
VS Code Version: 1.52.1
Project Type where issue experienced: Typescript library

**Comment by vmikeska** [comment]
The fix is just being published. I could just only find one occurrence of the  .split, seemed there was really missing a null check... please let me know if it helped

**Comment by bicarbon8** [comment]
looks like that did the trick! thanks for the speedy fix!!!
